/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Topic = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        reservationMenu = new javax.swing.JMenu();
        addReservationMenuItem = new javax.swing.JMenuItem();
        updateDeleteReservationMenuItem = new javax.swing.JMenuItem();
        reservationsListMenuItem = new javax.swing.JMenuItem();
        customersMenu = new javax.swing.JMenu();
        addCustomerMenuItem = new javax.swing.JMenuItem();
        updateDeleteCustomersMenuItem = new javax.swing.JMenuItem();
        customersAllMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home - RMS");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        Topic.setFont(new java.awt.Font("Goudy Old Style", 1, 30)); // NOI18N
        Topic.setForeground(new java.awt.Color(0, 102, 255));
        Topic.setText("Welcome to the Reservation Management System");

        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RMS-Home.png"))); // NOI18N
        background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backgroundMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Topic))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Topic, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        reservationMenu.setText("Reservations");
        reservationMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationMenuActionPerformed(evt);
            }
        });

        addReservationMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        addReservationMenuItem.setText("Add Reservation");
        addReservationMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addReservationMenuItemActionPerformed(evt);
            }
        });
        reservationMenu.add(addReservationMenuItem);

        updateDeleteReservationMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        updateDeleteReservationMenuItem.setText("Update Or Delete Reservation");
        updateDeleteReservationMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDeleteReservationMenuItemActionPerformed(evt);
            }
        });
        reservationMenu.add(updateDeleteReservationMenuItem);

        reservationsListMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        reservationsListMenuItem.setText("All Reservations");
        reservationsListMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationsListMenuItemActionPerformed(evt);
            }
        });
        reservationMenu.add(reservationsListMenuItem);

        jMenuBar1.add(reservationMenu);

        customersMenu.setText("Customers");

        addCustomerMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        addCustomerMenuItem.setText("Add Customer ");
        addCustomerMenuItem.setToolTipText("");
        addCustomerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerMenuItemActionPerformed(evt);
            }
        });
        customersMenu.add(addCustomerMenuItem);

        updateDeleteCustomersMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        updateDeleteCustomersMenuItem.setText("Update Or Delete Customer ");
        updateDeleteCustomersMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDeleteCustomersMenuItemActionPerformed(evt);
            }
        });
        customersMenu.add(updateDeleteCustomersMenuItem);

        customersAllMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        customersAllMenuItem.setText("Customers List");
        customersAllMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customersAllMenuItemActionPerformed(evt);
            }
        });
        customersMenu.add(customersAllMenuItem);

        jMenuBar1.add(customersMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void reservationMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationMenuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_reservationMenuActionPerformed

    private void backgroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_backgroundMouseClicked

    private void addReservationMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addReservationMenuItemActionPerformed
        // TODO add your handling code here:
        new View.AddReservation().setVisible(true);
        
    }//GEN-LAST:event_addReservationMenuItemActionPerformed

    private void addCustomerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerMenuItemActionPerformed
        // TODO add your handling code here:
        new View.AddCustomer().setVisible(true);
    }//GEN-LAST:event_addCustomerMenuItemActionPerformed

    private void customersAllMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customersAllMenuItemActionPerformed
        // TODO add your handling code here:
        new View.CustomerList().setVisible(true);
    }//GEN-LAST:event_customersAllMenuItemActionPerformed

    private void reservationsListMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationsListMenuItemActionPerformed
        // TODO add your handling code here:
        new View.ReservationList().setVisible(true);
    }//GEN-LAST:event_reservationsListMenuItemActionPerformed

    private void updateDeleteCustomersMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDeleteCustomersMenuItemActionPerformed
        // TODO add your handling code here:
        new View.UpdateDeleteCustomers().setVisible(true);
    }//GEN-LAST:event_updateDeleteCustomersMenuItemActionPerformed

    private void updateDeleteReservationMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDeleteReservationMenuItemActionPerformed
        // TODO add your handling code here:
        new View.UpdateDeleteReservation().setVisible(true);
    }//GEN-LAST:event_updateDeleteReservationMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Topic;
    private javax.swing.JMenuItem addCustomerMenuItem;
    private javax.swing.JMenuItem addReservationMenuItem;
    private javax.swing.JLabel background;
    private javax.swing.JMenuItem customersAllMenuItem;
    private javax.swing.JMenu customersMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu reservationMenu;
    private javax.swing.JMenuItem reservationsListMenuItem;
    private javax.swing.JMenuItem updateDeleteCustomersMenuItem;
    private javax.swing.JMenuItem updateDeleteReservationMenuItem;
    // End of variables declaration//GEN-END:variables
}
